title: "âœ… Code Promo WISEWAND : AVISDEJULIE"
description: "DÃ©couvrez WISEWAND, l'outil parfait pour crÃ©er des fiches produit optimisÃ©es SEO. Utilisez le code promo AVISDEJULIE et bÃ©nÃ©ficiez de -10% Ã  vie."
tagline: " - 10% A VIE ! ðŸš€"
author: "Ludovic - AvisDeJulie.fr"

# SEO Meta Tags
lang: "fr"
logo: "/assets/images/logo_wisewand.png"

# Jekyll SEO Plugin
plugins:
  - jekyll-seo-tag

# RÃ©seaux sociaux
social:
  name: "AvisDeJulie"
  links:
    - "https://avisdejulie.fr"
    - "https://wisewand.ai/?fpr=ludovic64"

# Theme du site (ex: Cayman)
theme: jekyll-theme-cayman

# Exclure les fichiers inutiles pour le SEO
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

force_rebuild: true
